name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Start server
      run: |
        nohup npm start &
        sleep 5

    - name: Run Cypress tests
      run: npm run test

    - name: Install k6
      run: |
        sudo gpg -k
        sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install k6


    - name: Run k6 load test
      run: k6 run --out json=results.json nonFunctionalCases.js

    - name: Upload k6 results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: k6-results
        path: /results.json  

    - name: Stop server
      run: |
        pkill -f node

    - name : Test Report
      if : always()
      uses: actions/upload-artifact@v4
      with:
        name: Mochawesome HTML Report
        path: cypress/reports/html